# Generated by Django 5.1.1 on 2024-10-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='files/userPhotos/defaultUser.PNG', upload_to='app_cad_usuarios/files/userPhotos'),
        ),
    ]
