# Generated by Django 5.1.1 on 2024-11-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_usuario_date_joined_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='files/userPhotos/defaultUser.PNG', upload_to='media/files/userPhotos'),
        ),
    ]
