# Generated by Django 5.1.1 on 2024-11-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0005_alter_usuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
    ]
