# Generated by Django 5.1.1 on 2024-11-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0008_dadosarduino'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comentario',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='UsuarioArduino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=25)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
