# Generated by Django 5.1.1 on 2024-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0010_usuarionivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionivel',
            name='ciclos',
            field=models.IntegerField(default=0),
        ),
    ]
