# Generated by Django 5.1.1 on 2024-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0011_alter_usuarionivel_ciclos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarionivel',
            name='ciclos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciclos',
            field=models.IntegerField(default=0),
        ),
    ]
